### ISSUE TITLE
inject: process new baseline labeling

### ISSUE THREAD

**Issue by kzhsw** [website-local/mdn-local#848]
![图片](https://github.com/website-local/mdn-local/assets/120431159/19dee13f-d2fd-4317-8649-a182e3ff8844)
![图片](https://github.com/website-local/mdn-local/assets/120431159/42a5bbb0-524d-429a-ac50-c9841905f085)

Click to open / close
Mask image icon

**Comment by myfreeer** [comment]
Example [here](https://developer.mozilla.org/en-US/docs/Web/CSS/minmax), this seems to be based on native details.

**Comment by myfreeer** [comment]
![image](https://github.com/website-local/mdn-local/assets/17702502/d6fdc67d-6ea6-4b70-91e5-b45097e3842e)
![image](https://github.com/website-local/mdn-local/assets/17702502/e2f29f42-be63-42d6-b310-2cf36bb63bf1)
No need to process details, but need to fix masked icons
